### ISSUE TITLE
make stratos fails with cf-operator/kubecf

### ISSUE THREAD

**Issue by greygoo** [SUSE/catapult#106]
Description:

After deploying kubecf, when running `make stratos`, it will fail with a bunch of subsequent errors.

First error:
```
chuller@d10:/data/src/suse/catapult(master)> make stratos
make -s -C modules/stratos
/data/src/suse/catapult/buildkind /data/src/suse/catapult/modules/stratos
ℹ  🚀  kind ☸ kind  🎂  ./clean.sh ➤  Loading
configmap/cap-values patched
✅  🚀  kind ☸ kind 🎂  ./clean.sh ➤  Stratos removed
/data/src/suse/catapult/buildkind /data/src/suse/catapult/modules/stratos
ℹ  🚀  kind ☸ kind  🎂  ./chart.sh ➤  Loading
⚠  🚀  kind ☸ kind 🎂  ./chart.sh ➤  No stratos chart url given - using latest public release from kubernetes-charts.suse.com
$HELM_HOME has been configured at /data/src/suse/catapult/buildkind/.helm.
Not installing Tiller due to 'client-only' flag having been set
"suse" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "suse" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
console/Chart.yaml
console/values.yaml
console/templates/__helpers.tpl
console/templates/deployment.yaml
console/templates/ingress.yaml
console/templates/pre-install.yaml
console/templates/secrets.yaml
console/templates/service.yaml
console/templates/volume-migration.yaml
console/.helmignore
console/imagelist.txt
configmap/cap-values patched
✅  🚀  kind ☸ kind 🎂  ./chart.sh ➤  Stratos chart uncompressed
/data/src/suse/catapult/buildkind /data/src/suse/catapult/modules/stratos
ℹ  🚀  kind ☸ kind  🎂  ./gen-config.sh ➤  Loading
ℹ  🚀  kind ☸ kind  🎂  ./gen-config.sh ➤  Generating stratos config values from scf values
2020/02/19 16:47:47 error applying patch: yamlpatch replace operation does not apply: doc is missing path: /kube/registry/hostname
make[1]: *** [Makefile:13: gen-config] Error 1
```

The culprit here seems to be in `modules/scf/gen_config.sh`, the last block addition in that file only runs when ${SCF_OPERATOR} is false. Otherwise this block is never added, which then leaves you with an scf-config.yaml that is missing hostname, password and other entries.

Just moving the last `fi` in the file up a bit is not a quickfix, that then triggers other issues with kubecf/cf-coperator deployments itself. 

When manually working around the issue, the resulting scf-config-values.yaml looks as follows:

```
console:
  service:
    ingress:
      enabled: true
features:
  eirini:
    enabled: true
kube:
  organization: cap
  pod_cluster_ip_range: 0.0.0.0/0
  registry:
    hostname: registry.suse.com
    password: ""
    username: ""
  service_cluster_ip_range: 0.0.0.0/0
  storage_class: persistent
services:
  router:
    externalIPs:
    - 172.17.0.2
    - 172.17.0.2
    type: LoadBalancer
  ssh-proxy:
    externalIPs:
    - 172.17.0.2
    - 172.17.0.2
    type: LoadBalancer
  tcp-router:
    externalIPs:
    - 172.17.0.2
    - 172.17.0.2
    port_range:
      end: 20008
      start: 20000
    type: LoadBalancer
system_domain: 172.17.0.2.nip.io
```

```
Error: render error in "console/templates/pre-install.yaml": template: console/templates/pre-install.yaml:15:21: executing "console/templates/pre-install.yaml" at <.Values.kube.storage_class.persistent>: can't evaluate field persistent in type interface {}
```

This is triggered by the storageclass entry not being correct. It needs to be

```
  storage_class:
    persistent: persistent
```

When working around this, the remaining issue that appears is 

```
ℹ  🚀  kind ☸ kind  🎂  ./install.sh ➤  Deploying stratos
Error: render error in "console/templates/ingress.yaml": template: console/templates/__helpers.tpl:151:3: executing "ingress.host" at <required "Host name is required" $host>: error calling required: Host name is required
```

That error is triggered as the scf-config-values.yaml for kubecf does not contain an /env/DOMAIN entry anymore which is needed by stratos. As catapult automatically creates the config for stratos from the scf config file, this needs to be added additionally.

**Comment by greygoo** [comment]
One remaining problem after the above workaround is that the deployed stratos won;t get an ip address assigned, which is due to the config missing the following entries:

```
console:
  service:
    externalIPs: ["$some_ip"]
    servicePort: 8443
```
