### ISSUE TITLE
Automate stratos metrics deployment

### ISSUE THREAD

**Issue by viccuad** [SUSE/catapult#82]
Add a new make target to be able to deploy Stratos Metrics as explained here:
https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/#sec-cap-stratos-metrics

In case of deploying from a staging repo, 
supplying the registry overrides for the staging registry correctly, see:

https://github.com/SUSE/stratos-metrics/blob/master/README.md#deploying-metrics-from-a-private-image-repository

As an example, here's the helm chart values for a staging registry configuration for metrics:
```
kube:
  registry:
    hostname: staging.registry.X
    username: <USER>
    password: <PASSWORD>
    email: default

prometheus:
  imagePullSecrets:
  - name: regsecret
```
